name: moe-os
description: Moe's Persönliches uBlue Image
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40
modules:
  # Default Repo Packages
  - type: rpm-ostree
    repos:
    install:
       - steam-devices
       - steam
       - mesa-va-drivers-freeworld.i686
       - mesa-vdpau-drivers-freeworld.i686
       - mesa-vdpau-drivers-freeworld.x86_64
       - ibm-plex-fonts-all
       - mangohud
       - gamemode
    remove:
       - firefox
       - firefox-langpacks
       - wireguard-tools
       - google-noto-sans-balinese-fonts
       - google-noto-sans-cjk-fonts
       - google-noto-sans-javanese-fonts
       - google-noto-sans-sundanese-fonts
       - nvtop
       - solaar-udev
       - openrgb-udev-rules
       - oversteer-udev
       - tcpdump
       - tmux
       - libratbag-ratbagd
       
  # Customization for KDE Plasma
 # - type: rpm-ostree
 #   repos:
 #      - https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/repo/fedora-%OS_VERSION%/luisbocanegra-kde-material-you-colors-fedora-%OS_VERSION%.repo
 #      - https://copr.fedorainfracloud.org/coprs/errornointernet/klassy/repo/fedora-%OS_VERSION%/errornointernet-klassy-fedora-%OS_VERSION%.repo
 #   install:
 #      - klassy
 #      - kde-material-you-colors
 #      - python-materialyoucolor
 #      - python-pywal
       
  # Gamescope Git
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/vulongm/gamescope-git/repo/fedora-%OS_VERSION%/vulongm-gamescope-git-fedora-%OS_VERSION%.repo
    install:
       - gamescope
       
  # Gamescope Shaders
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
    install:
       - gamescope-shaders
       - sdgyrodsu
       
  # Gamescope Session
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara-%OS_VERSION%/repo/fedora-%OS_VERSION%/gloriouseggroll-nobara-%OS_VERSION%-fedora-%OS_VERSION%.repo?arch=x86_64
    install:
       - gamescope-session-plus
       - gamescope-session-steam
       
  # Printer Driver
  - type: rpm-ostree
    repos:
       - https://negativo17.org/repos/fedora-uld.repo
    install:
       - uld
       
  # AKmods for Controller Dongle Support
  - type: akmods
    base: main
    install:
       - xone
       - xpadneo
       
 # Flatpaks
  - type: default-flatpaks
    install:
       - org.mozilla.firefox
    
  - type: signing
