name: moe-os
description: Moe's Persönliches uBlue Image
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40
modules:
  # Default Repo Packages
  - type: rpm-ostree
    repos:
    install:
       - steam-devices
       - steam
       - mesa-va-drivers-freeworld.i686
       - mesa-vdpau-drivers-freeworld.i686
       - mesa-vdpau-drivers-freeworld.x86_64
     #  - xwaylandvideobridge
       - ibm-plex-fonts-all
       - mangohud
       - gamemode
       - gnome-console
       # Citrix Client
       - adw-gtk3-theme
       - https://downloads.citrix.com/22718/ICAClient-rhel-24.5.0.76-0.x86_64.rpm?__gda__=exp=1721926070~acl=/*~hmac=1af9f84a90b1d1f8f3382917d51651eec0d86e7adfe6285b83757f22f3a75ed0
    remove:
       - gnome-terminal
       - gnome-terminal-nautilus
       - firefox
       - firefox-langpacks
       - wireguard-tools
       - google-noto-sans-balinese-fonts
       - google-noto-sans-cjk-fonts
       - google-noto-sans-javanese-fonts
       - google-noto-sans-sundanese-fonts
       - nvtop
       - solaar-udev
       - openrgb-udev-rules
       - oversteer-udev
       - tcpdump
       - tmux
       - libratbag-ratbagd
       - htop
       
  # Customization
#  - type: rpm-ostree
#    repos:
#       - https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/repo/fedora-%OS_VERSION%/luisbocanegra-kde-material-you-colors-fedora-%OS_VERSION%.repo
#       - https://copr.fedorainfracloud.org/coprs/errornointernet/klassy/repo/fedora-%OS_VERSION%/errornointernet-klassy-fedora-%OS_VERSION%.repo
#    install:
#       - klassy
#       - kde-material-you-colors
#       - python-materialyoucolor
#       - python-pywal
       
  # Gamescope Git
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/vulongm/gamescope-git/repo/fedora-%OS_VERSION%/vulongm-gamescope-git-fedora-%OS_VERSION%.repo
    install:
       - gamescope
       
  # Gamescope Session
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara-%OS_VERSION%/repo/fedora-%OS_VERSION%/gloriouseggroll-nobara-%OS_VERSION%-fedora-%OS_VERSION%.repo?arch=x86_64
    install:
       - gamescope-session-plus
       - gamescope-session-steam
       
  # Printer Driver
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo

       - https://negativo17.org/repos/fedora-uld.repo
    install:
       - uld
       
    # Joystickwake   
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
    install:
       - joystickwake
       - ds-inhibit
       
  # AKmods for Controller Dongle Support
  - type: akmods
    base: main
    install:
       - xone
       - xpadneo

  # Use the default flatpak module to setup repos. We want to install flatpaks manually
  - type: default-flatpaks
    system:  

  # Gnome Extensions
  - type: gnome-extensions
    install:
       - Night Theme Switcher
       - AppIndicator and KStatusNotifierItem Support
    uninstall:

  - type: signing
