name: moe.os
description: Moe's Persönliches uBlue Image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40

modules:
  - type: rpm-ostree
    repos:
       #- https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
    remove:
       - firefox
       - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
       repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
       repo-name: flathub
       repo-title: "Flathub (system-wide)"
    install:
         - org.mozilla.firefox
         - com.dec05eba.gpu_screen_recorder
         - dev.vencord.Vesktop
         - net.davidotek.pupgui2
         - org.blender.Blender
         - org.kde.elisa
         - org.kde.gwenview
         - org.kde.haruna
         - org.kde.isoimagewriter
         - org.kde.kcolorchooser
         - org.kde.kdenlive
         - org.kde.kdiff3
         - org.kde.kget
         - org.kde.kontact
         - org.kde.kolourpaint
         - org.kde.kommit
         - org.kde.krita
         - org.kde.kruler
         - org.kde.okular
         - org.kde.skanpage
         - com.ktechpit.whatsie
  - type: signing

