name: moe-os
description: Moe's Persönliches uBlue Image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40
modules:
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/repo/fedora-%OS_VERSION%/luisbocanegra-kde-material-you-colors-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/errornointernet/klassy/repo/fedora-%OS_VERSION%/errornointernet-klassy-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/vulongm/gamescope-git/repo/fedora-%OS_VERSION%/vulongm-gamescope-git-fedora-%OS_VERSION%.repo
    install:
       - klassy
       - kde-material-you-colors
       - python-materialyoucolor
       - python-pywal
       - steam-devices
    remove:
       - firefox
       - firefox-langpacks
       - distrobox
       - wireguard-tools
       - google-noto-sans-balinese-fonts
       - google-noto-sans-cjk-fonts
       - google-noto-sans-javanese-fonts
       - google-noto-sans-sundanese-fonts
  - type: default-flatpaks
    notify: true
    user: 
    install:
      - com.valvesoftware.Steam
      - com.valvesoftware.Steam.Utility.InhibitScreensaver
      - org.freedesktop.Platform.VulkanLayer.gamescope
      - org.mozilla.firefox
      - com.dec05eba.gpu_screen_recorder
      - dev.vencord.Vesktop
      - net.davidotek.pupgui2
      - org.blender.Blender
      - org.kde.elisa
      - org.kde.gwenview
      - org.kde.haruna
      - org.kde.isoimagewriter
      - org.kde.kcolorchooser
      - org.kde.kdenlive
      - org.kde.kdiff3
      - org.kde.kget
      - org.kde.kontact
      - org.kde.kolourpaint
      - org.kde.kommit
      - org.kde.krita
      - org.kde.kruler
      - org.kde.okular
      - org.kde.skanpage
      - org.kde.digikam
      - com.ktechpit.whatsie
      - org.kde.kdf
      - io.github.jonmagon.kdiskmark
      - net.davidotek.pupgui2
      - org.kde.marble
      - org.kde.kompare
      - org.kde.kgeography
      - org.kde.ktrip
      - org.kde.koko
      - org.kde.audiotube
  - type: script
    snippets:
       - "flatpak override --filesystem=xdg-config/gtk-3.0:ro"
       - "flatpak override --filesystem=xdg-config/gtk-4.0:ro"
  - type: signing
