name: moe-os
description: Moe's Persönliches uBlue Image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40

modules:
  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/luisbocanegra/kde-material-you-colors/repo/fedora-%OS_VERSION%/luisbocanegra-kde-material-you-colors-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/errornointernet/klassy/repo/fedora-%OS_VERSION%/errornointernet-klassy-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/vulongm/gamescope-git/repo/fedora-%OS_VERSION%/vulongm-gamescope-git-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/vulongm/gamemode-git/repo/fedora-%OS_VERSION%/vulongm-gamemode-git-fedora-%OS_VERSION%.repo
    install:
       - klassy
       - kde-material-you-colors
       - python-materialyoucolor
       - python-pywal
       - steam
       - steam-devices
       - gamescope
    remove:
       - firefox
       - firefox-langpacks
       - distrobox
       - wireguard-tools
       - solaar-udev
       - libratbag-ratbagd
       - oversteer-udev
       - solaar-udev
       - openrgb-udev-rules
  - type: default-flatpaks
    notify: true
    system:
    install:
         - org.mozilla.firefox
         - com.dec05eba.gpu_screen_recorder
         - dev.vencord.Vesktop
         - net.davidotek.pupgui2
         - org.blender.Blender
         - org.kde.elisa
         - org.kde.gwenview
         - org.kde.haruna
         - org.kde.isoimagewriter
         - org.kde.kcolorchooser
         - org.kde.kdenlive
         - org.kde.kdiff3
         - org.kde.kget
         - org.kde.kontact
         - org.kde.kolourpaint
         - org.kde.kommit
         - org.kde.krita
         - org.kde.kruler
         - org.kde.okular
         - org.kde.skanpage
         - com.ktechpit.whatsie
  - type: signing

